"""Frozen outputs generated by the supplied R package, not by Python.

Regenerate using Rscript tests/reference/generate.R. No R is needed in CI.
Variances near zero use absolute tolerances; relative error there is meaningless.
"""

from pathlib import Path
import numpy as np
import pandas as pd
import pytest
from pyspats import fit_trial, SpatialSpec, SpATSControl
from pyspats.families import poisson, binomial

ROOT = Path(__file__).parent / "reference"


def fit_case(case):
    data = pd.read_csv(ROOT / "field.csv")
    kw = {}
    kind = case.rsplit("_", 1)[0] if "_" in case else "PSANOVA"
    random = not case.endswith("_fixed")
    if case == "missing":
        data.loc[[1, 9, 49], "yield"] = np.nan
        data.loc[19, "weight"] = 0
    if case in ("weighted", "missing"):
        kw["weights"] = "weight"
    if case == "weighted":
        kw["offset"] = "off"
    if case == "populations":
        kw["geno_decomp"] = "population"
    if case == "poisson":
        kw["family"] = poisson()
    if case == "binomial":
        kw["family"] = binomial()
    spec = SpatialSpec(
        "col",
        "row",
        nseg=(6, 8),
        nest_div=2,
        kind=kind if case not in ("unequal_degree", "unequal_order") else "PSANOVA",
    )
    if case == "unequal_degree":
        spec = SpatialSpec("col", "row", nseg=(6, 8), nest_div=2, degree=(2, 4))
    if case == "unequal_order":
        spec = SpatialSpec(
            "col",
            "row",
            nseg=(6, 8),
            nest_div=2,
            degree=(2, 3),
            penalty_order=(1, 3),
            kind="SAP",
        )
    if case == "centered":
        spec = SpatialSpec("col", "row", nseg=(6, 8), nest_div=2, center=True)
    return fit_trial(
        data=data,
        response={"poisson": "count", "binomial": "binary"}.get(case, "yield"),
        genotype="geno",
        genotype_as_random=random,
        fixed=["treatment"],
        random=["block"],
        spatial=spec,
        control=SpATSControl(tolerance=1e-9, max_iter=1000),
        **kw,
    )


@pytest.mark.parametrize(
    "case",
    [
        f"{kind}_{g}"
        for kind in ("PSANOVA", "SAP", "SAP.ANOVA")
        for g in ("fixed", "random")
    ]
    + [
        "weighted",
        "missing",
        "centered",
        "populations",
        "poisson",
        "binomial",
        "unequal_degree",
        "unequal_order",
    ],
)
def test_r_reference(case):
    model = fit_case(case)
    ref = pd.read_csv(ROOT / f"{case}_fitted.csv")
    np.testing.assert_allclose(model.fitted_values, ref.fitted, atol=5e-6, rtol=1e-7)
    np.testing.assert_allclose(
        model.predict(return_se=True).se_link, ref.se, atol=5e-6, rtol=1e-5
    )
    components = pd.read_csv(ROOT / f"{case}_components.csv")
    # R stores genotype/block components ahead of spatial components.
    names = list(model.var_comp)
    spatial = len(model._basis.names)
    order = names[spatial:] + names[:spatial]
    np.testing.assert_allclose(
        [model.var_comp[n] for n in order], components.variance, rtol=1e-4, atol=1e-5
    )
    np.testing.assert_allclose(
        [model.effective_dim[n] for n in order], components.ed, rtol=1e-5, atol=5e-6
    )
    stats = pd.read_csv(ROOT / f"{case}_stats.csv").iloc[0]
    np.testing.assert_allclose(model.psi, stats.psi, rtol=1e-6)
    np.testing.assert_allclose(model.deviance, stats.objective, atol=1e-6, rtol=1e-7)
    if "h2" in stats and np.isfinite(stats.h2):
        assert model.heritability == pytest.approx(stats.h2, abs=1e-6)
    assert model.converged


@pytest.mark.parametrize("random", [False, True])
def test_real_wheat_trial(random):
    from pyspats.datasets import load_wheatdata

    model = fit_trial(
        data=load_wheatdata(),
        response="yield",
        genotype="geno",
        genotype_as_random=random,
        spatial=SpatialSpec("col", "row"),
        random=["R", "C"],
        control=SpATSControl(tolerance=1e-9, max_iter=1000),
    )
    tag = "wheat_random" if random else "wheat_fixed"
    ref = pd.read_csv(ROOT / f"{tag}_fitted.csv")
    np.testing.assert_allclose(model.fitted_values, ref.fitted, atol=1e-4, rtol=1e-7)
    comp = pd.read_csv(ROOT / f"{tag}_components.csv")
    names = list(model.var_comp)
    order = names[5:] + names[:5]
    np.testing.assert_allclose(
        [model.var_comp[n] for n in order], comp.variance, rtol=1e-4, atol=1e-5
    )
    np.testing.assert_allclose(
        [model.effective_dim[n] for n in order], comp.ed, rtol=1e-5, atol=5e-6
    )
    assert model.converged


def test_existing_sorghum_trial():
    data = pd.read_csv(ROOT.parent.parent / "examples/sorghum_data.csv")
    with pytest.warns(UserWarning, match="without observed"):
        model = fit_trial(
            data=data,
            response="EstimatedPlotYield",
            genotype="PINumber",
            genotype_as_random=True,
            spatial=SpatialSpec("Column", "Row", nest_div=2),
            fixed=["Treatment"],
            random=["Block"],
            control=SpATSControl(tolerance=1e-7, max_iter=1000),
        )
    ref = pd.read_csv(ROOT / "sorghum_fitted.csv")
    # Unobserved-only factor levels deliberately have no Python predictions.
    use = np.isfinite(model.fitted_values)
    np.testing.assert_allclose(
        model.fitted_values[use], ref.fitted[use], atol=5e-5, rtol=1e-7
    )
    assert model.n_obs == 1162 and model.converged
